sudo: false
language: java
jdk:
- oraclejdk8
env:
  global:
  - SONATYPE_USERNAME=davidmoten
  - secure: HdYgKqAqTG8sVkWFJ5bijpUdM34BvMSiFkgu2PjQ408kjYS9Uk+6tJgvxC9heFjv120FBgfGYazyO9oC5RYOjQglLVl/iD8cZ2Za966jazvfFln/YHaTyS2RnUbE8S54bKX5svFEx0JJWimovW5BtbeFP76iaiw9h+cPZUZIDig=
  - secure: jWOdssMm/KD7EWkRYZj/IxUSgqO736tARwbvvSYtFk5MWEhou9DIntCEeRoUgwQ9qgsZuOHkp2oay7QzRGejw1ec6Etw1ti9incbQqmmStgB4hLefD9PdRFqoBN/Wx6/hG77FSwd7YtJk2/uUiJFiVhDbDINru1Hh0GY1GXo8mQ=

after_success:
  - src/deploy/deploy.sh
